#data0-minio-pool-0-0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data1-n2
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data1-n3
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /data1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data2-n2
spec:
  capacity:
    storage: 22Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data2-n3
spec:
  capacity:
    storage: 22Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /data2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: log
spec:
  capacity:
    storage: 22Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: search
spec:
  capacity:
    storage: 22Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /search
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - n2